### ISSUE TITLE
not able to deploy

### ISSUE THREAD

**Issue by flaskvol** [Appeza/tg-mirror-leech-bot#20]
### Describe the Bug

2021-12-30T14:02:00.529055+00:00 app[web.1]:     return _get_module_details(pkg_main_name, error)
2021-12-30T14:02:00.529055+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
2021-12-30T14:02:00.529056+00:00 app[web.1]:     __import__(pkg_name)
2021-12-30T14:02:00.529056+00:00 app[web.1]:   File "/usr/src/app/bot/__init__.py", line 278, in <module>
2021-12-30T14:02:00.529057+00:00 app[web.1]:     TORRENT_DIRECT_LIMIT = float(TORRENT_DIRECT_LIMIT)
2021-12-30T14:02:00.529057+00:00 app[web.1]: ValueError: could not convert string to float: '800 GB'
2021-12-30T14:02:01.096850+00:00 heroku[router]: at=info method=GET path="/" host=cyberboymirror.herokuapp.com request_id=e9bb3591-69d6-49a6-8626-acb78183fb62 fwd="54.74.155.253" dyno=web.1 connect=0ms service=2ms status=200 bytes=338 protocol=https
2021-12-30T14:02:34.175494+00:00 heroku[web.1]: Process exited with status 1
2021-12-30T14:02:34.243015+00:00 heroku[web.1]: State changed from up to crashed
2021-12-30T14:03:14.605629+00:00 heroku[web.1]: State changed from crashed to starting
2021-12-30T14:03:13.107012+00:00 app[api]: Running release v5 commands by user lsnclfo869@trashmails.xyz
2021-12-30T14:03:13.122023+00:00 app[api]: @ref:postgresql-contoured-70883 completed provisioning, setting DATABASE_URL. by user lsnclfo869@trashmails.xyz
2021-12-30T14:03:13.107012+00:00 app[api]: Attach DATABASE (@ref:postgresql-contoured-70883) by user lsnclfo869@trashmails.xyz
2021-12-30T14:03:13.122023+00:00 app[api]: Release v6 created by user lsnclfo869@trashmails.xyz
2021-12-30T14:03:41.857301+00:00 heroku[web.1]: Starting process with command `bash start.sh`
2021-12-30T14:03:45.556138+00:00 app[web.1]: 2021-12-30 14:03:45,555 - root - INFO - Initializing Aria2c
2021-12-30T14:03:45.557040+00:00 app[web.1]: 2021-12-30 14:03:45,556 - bot - INFO - Generating USER_SESSION_STRING
2021-12-30T14:03:45.557807+00:00 app[web.1]: 2021-12-30 14:03:45,557 - root - WARNING - UPTOBOX_TOKEN not provided!
2021-12-30T14:03:45.559270+00:00 app[web.1]: Traceback (most recent call last):
2021-12-30T14:03:45.559271+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
2021-12-30T14:03:45.559271+00:00 app[web.1]:     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
2021-12-30T14:03:45.559272+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
2021-12-30T14:03:45.559272+00:00 app[web.1]:     return _get_module_details(pkg_main_name, error)
2021-12-30T14:03:45.559272+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
2021-12-30T14:03:45.559273+00:00 app[web.1]:     __import__(pkg_name)
2021-12-30T14:03:45.559273+00:00 app[web.1]:   File "/usr/src/app/bot/__init__.py", line 278, in <module>
2021-12-30T14:03:45.559274+00:00 app[web.1]:     TORRENT_DIRECT_LIMIT = float(TORRENT_DIRECT_LIMIT)
2021-12-30T14:03:45.559274+00:00 app[web.1]: ValueError: could not convert string to float: '800 GB'
2021-12-30T14:03:45.561350+00:00 heroku[web.1]: State changed from starting to up
2021-12-30T14:03:45.076058+00:00 app[web.1]: [2021-12-30 14:03:45 +0000] [10] [INFO] Starting gunicorn 20.1.0
2021-12-30T14:03:45.076478+00:00 app[web.1]: [2021-12-30 14:03:45 +0000] [10] [INFO] Listening at: http://0.0.0.0:15067 (10)
2021-12-30T14:03:45.076520+00:00 app[web.1]: [2021-12-30 14:03:45 +0000] [10] [INFO] Using worker: aiohttp.GunicornWebWorker
2021-12-30T14:03:45.080506+00:00 app[web.1]: [2021-12-30 14:03:45 +0000] [40] [INFO] Booting worker with pid: 40
2021-12-30T14:03:46.936458+00:00 heroku[router]: at=info method=GET path="/" host=cyberboymirror.herokuapp.com request_id=8d597df7-5a3f-4adf-a1b3-fb5d6c738f9f fwd="18.203.178.177" dyno=web.1 connect=0ms service=1ms status=200 bytes=338 protocol=https
2021-12-30T14:04:19.689663+00:00 heroku[web.1]: Process exited with status 1
2021-12-30T14:04:19.761911+00:00 heroku[web.1]: State changed from up to crashed
2021-12-30T14:05:25.034469+00:00 heroku[web.1]: State changed from crashed to starting
2021-12-30T14:05:50.456211+00:00 heroku[web.1]: Starting process with command `bash start.sh`
2021-12-30T14:05:52.428407+00:00 app[web.1]: [2021-12-30 14:05:52 +0000] [10] [INFO] Starting gunicorn 20.1.0
2021-12-30T14:05:52.428785+00:00 app[web.1]: [2021-12-30 14:05:52 +0000] [10] [INFO] Listening at: http://0.0.0.0:50785 (10)
2021-12-30T14:05:52.428826+00:00 app[web.1]: [2021-12-30 14:05:52 +0000] [10] [INFO] Using worker: aiohttp.GunicornWebWorker
2021-12-30T14:05:52.432550+00:00 app[web.1]: [2021-12-30 14:05:52 +0000] [38] [INFO] Booting worker with pid: 38
2021-12-30T14:05:52.563938+00:00 heroku[web.1]: State changed from starting to up
2021-12-30T14:05:52.994681+00:00 app[web.1]: 2021-12-30 14:05:52,994 - root - INFO - Initializing Aria2c
2021-12-30T14:05:52.995719+00:00 app[web.1]: 2021-12-30 14:05:52,994 - bot - INFO - Generating USER_SESSION_STRING
2021-12-30T14:05:52.996430+00:00 app[web.1]: 2021-12-30 14:05:52,996 - root - WARNING - UPTOBOX_TOKEN not provided!
2021-12-30T14:05:52.998275+00:00 app[web.1]: Traceback (most recent call last):
2021-12-30T14:05:52.998276+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
2021-12-30T14:05:52.998276+00:00 app[web.1]:     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
2021-12-30T14:05:52.998276+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
2021-12-30T14:05:52.998277+00:00 app[web.1]:     return _get_module_details(pkg_main_name, error)
2021-12-30T14:05:52.998277+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
2021-12-30T14:05:52.998290+00:00 app[web.1]:     __import__(pkg_name)
2021-12-30T14:05:52.998291+00:00 app[web.1]:   File "/usr/src/app/bot/__init__.py", line 278, in <module>
2021-12-30T14:05:52.998291+00:00 app[web.1]:     TORRENT_DIRECT_LIMIT = float(TORRENT_DIRECT_LIMIT)
2021-12-30T14:05:52.998291+00:00 app[web.1]: ValueError: could not convert string to float: '800 GB'
2021-12-30T14:05:54.324088+00:00 heroku[router]: at=info method=GET path="/" host=cyberboymirror.herokuapp.com request_id=2964b15b-114a-4e56-9b7f-c31d2f750e86 fwd="54.154.227.157" dyno=web.1 connect=0ms service=1ms status=200 bytes=338 protocol=https
2021-12-30T14:06:26.379463+00:00 heroku[web.1]: State changed from up to crashed
2021-12-30T14:06:26.304136+00:00 heroku[web.1]: Process exited with status 1

### Add Logs

2021-12-30T14:02:00.529055+00:00 app[web.1]:     return _get_module_details(pkg_main_name, error)
2021-12-30T14:02:00.529055+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
2021-12-30T14:02:00.529056+00:00 app[web.1]:     __import__(pkg_name)
2021-12-30T14:02:00.529056+00:00 app[web.1]:   File "/usr/src/app/bot/__init__.py", line 278, in <module>
2021-12-30T14:02:00.529057+00:00 app[web.1]:     TORRENT_DIRECT_LIMIT = float(TORRENT_DIRECT_LIMIT)
2021-12-30T14:02:00.529057+00:00 app[web.1]: ValueError: could not convert string to float: '800 GB'
2021-12-30T14:02:01.096850+00:00 heroku[router]: at=info method=GET path="/" host=cyberboymirror.herokuapp.com request_id=e9bb3591-69d6-49a6-8626-acb78183fb62 fwd="54.74.155.253" dyno=web.1 connect=0ms service=2ms status=200 bytes=338 protocol=https
2021-12-30T14:02:34.175494+00:00 heroku[web.1]: Process exited with status 1
2021-12-30T14:02:34.243015+00:00 heroku[web.1]: State changed from up to crashed
2021-12-30T14:03:14.605629+00:00 heroku[web.1]: State changed from crashed to starting
2021-12-30T14:03:13.107012+00:00 app[api]: Running release v5 commands by user lsnclfo869@trashmails.xyz
2021-12-30T14:03:13.122023+00:00 app[api]: @ref:postgresql-contoured-70883 completed provisioning, setting DATABASE_URL. by user lsnclfo869@trashmails.xyz
2021-12-30T14:03:13.107012+00:00 app[api]: Attach DATABASE (@ref:postgresql-contoured-70883) by user lsnclfo869@trashmails.xyz
2021-12-30T14:03:13.122023+00:00 app[api]: Release v6 created by user lsnclfo869@trashmails.xyz
2021-12-30T14:03:41.857301+00:00 heroku[web.1]: Starting process with command `bash start.sh`
2021-12-30T14:03:45.556138+00:00 app[web.1]: 2021-12-30 14:03:45,555 - root - INFO - Initializing Aria2c
2021-12-30T14:03:45.557040+00:00 app[web.1]: 2021-12-30 14:03:45,556 - bot - INFO - Generating USER_SESSION_STRING
2021-12-30T14:03:45.557807+00:00 app[web.1]: 2021-12-30 14:03:45,557 - root - WARNING - UPTOBOX_TOKEN not provided!
2021-12-30T14:03:45.559270+00:00 app[web.1]: Traceback (most recent call last):
2021-12-30T14:03:45.559271+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
2021-12-30T14:03:45.559271+00:00 app[web.1]:     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
2021-12-30T14:03:45.559272+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
2021-12-30T14:03:45.559272+00:00 app[web.1]:     return _get_module_details(pkg_main_name, error)
2021-12-30T14:03:45.559272+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
2021-12-30T14:03:45.559273+00:00 app[web.1]:     __import__(pkg_name)
2021-12-30T14:03:45.559273+00:00 app[web.1]:   File "/usr/src/app/bot/__init__.py", line 278, in <module>
2021-12-30T14:03:45.559274+00:00 app[web.1]:     TORRENT_DIRECT_LIMIT = float(TORRENT_DIRECT_LIMIT)
2021-12-30T14:03:45.559274+00:00 app[web.1]: ValueError: could not convert string to float: '800 GB'
2021-12-30T14:03:45.561350+00:00 heroku[web.1]: State changed from starting to up
2021-12-30T14:03:45.076058+00:00 app[web.1]: [2021-12-30 14:03:45 +0000] [10] [INFO] Starting gunicorn 20.1.0
2021-12-30T14:03:45.076478+00:00 app[web.1]: [2021-12-30 14:03:45 +0000] [10] [INFO] Listening at: http://0.0.0.0:15067 (10)
2021-12-30T14:03:45.076520+00:00 app[web.1]: [2021-12-30 14:03:45 +0000] [10] [INFO] Using worker: aiohttp.GunicornWebWorker
2021-12-30T14:03:45.080506+00:00 app[web.1]: [2021-12-30 14:03:45 +0000] [40] [INFO] Booting worker with pid: 40
2021-12-30T14:03:46.936458+00:00 heroku[router]: at=info method=GET path="/" host=cyberboymirror.herokuapp.com request_id=8d597df7-5a3f-4adf-a1b3-fb5d6c738f9f fwd="18.203.178.177" dyno=web.1 connect=0ms service=1ms status=200 bytes=338 protocol=https
2021-12-30T14:04:19.689663+00:00 heroku[web.1]: Process exited with status 1
2021-12-30T14:04:19.761911+00:00 heroku[web.1]: State changed from up to crashed
2021-12-30T14:05:25.034469+00:00 heroku[web.1]: State changed from crashed to starting
2021-12-30T14:05:50.456211+00:00 heroku[web.1]: Starting process with command `bash start.sh`
2021-12-30T14:05:52.428407+00:00 app[web.1]: [2021-12-30 14:05:52 +0000] [10] [INFO] Starting gunicorn 20.1.0
2021-12-30T14:05:52.428785+00:00 app[web.1]: [2021-12-30 14:05:52 +0000] [10] [INFO] Listening at: http://0.0.0.0:50785 (10)
2021-12-30T14:05:52.428826+00:00 app[web.1]: [2021-12-30 14:05:52 +0000] [10] [INFO] Using worker: aiohttp.GunicornWebWorker
2021-12-30T14:05:52.432550+00:00 app[web.1]: [2021-12-30 14:05:52 +0000] [38] [INFO] Booting worker with pid: 38
2021-12-30T14:05:52.563938+00:00 heroku[web.1]: State changed from starting to up
2021-12-30T14:05:52.994681+00:00 app[web.1]: 2021-12-30 14:05:52,994 - root - INFO - Initializing Aria2c
2021-12-30T14:05:52.995719+00:00 app[web.1]: 2021-12-30 14:05:52,994 - bot - INFO - Generating USER_SESSION_STRING
2021-12-30T14:05:52.996430+00:00 app[web.1]: 2021-12-30 14:05:52,996 - root - WARNING - UPTOBOX_TOKEN not provided!
2021-12-30T14:05:52.998275+00:00 app[web.1]: Traceback (most recent call last):
2021-12-30T14:05:52.998276+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
2021-12-30T14:05:52.998276+00:00 app[web.1]:     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
2021-12-30T14:05:52.998276+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
2021-12-30T14:05:52.998277+00:00 app[web.1]:     return _get_module_details(pkg_main_name, error)
2021-12-30T14:05:52.998277+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
2021-12-30T14:05:52.998290+00:00 app[web.1]:     __import__(pkg_name)
2021-12-30T14:05:52.998291+00:00 app[web.1]:   File "/usr/src/app/bot/__init__.py", line 278, in <module>
2021-12-30T14:05:52.998291+00:00 app[web.1]:     TORRENT_DIRECT_LIMIT = float(TORRENT_DIRECT_LIMIT)
2021-12-30T14:05:52.998291+00:00 app[web.1]: ValueError: could not convert string to float: '800 GB'
2021-12-30T14:05:54.324088+00:00 heroku[router]: at=info method=GET path="/" host=cyberboymirror.herokuapp.com request_id=2964b15b-114a-4e56-9b7f-c31d2f750e86 fwd="54.154.227.157" dyno=web.1 connect=0ms service=1ms status=200 bytes=338 protocol=https
2021-12-30T14:06:26.379463+00:00 heroku[web.1]: State changed from up to crashed
2021-12-30T14:06:26.304136+00:00 heroku[web.1]: Process exited with status 1

### Additional info

When i deploy on heroku , then it happens

**Comment by manansantoki** [comment]
Read your error ! 

Don't Put 'GB' in TORRENT_DIRECT_LIMIT

**Comment by flaskvol** [comment]
then , what to put ?

**Comment by iamSMMH** [comment]
Don't put High GB like 800 GB in TORRENT_DIRECT_LIMIT... Put below 100 GB

**Comment by flaskvol** [comment]
ok
