### ISSUE TITLE
Crashing after recent update [Heroku]

### ISSUE THREAD

**Issue by tmatzxzone** [Appeza/tg-mirror-leech-bot#26]
### Describe the Bug

Cannot deploy to heroku after the recent update 

### Add Logs

2022-01-17T09:10:39.252554+00:00 app[web.1]: Traceback (most recent call last):
2022-01-17T09:10:39.252565+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
2022-01-17T09:10:39.252566+00:00 app[web.1]:     return _run_code(code, main_globals, None,
2022-01-17T09:10:39.252567+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
2022-01-17T09:10:39.252568+00:00 app[web.1]:     exec(code, run_globals)
2022-01-17T09:10:39.252568+00:00 app[web.1]:   File "/usr/src/app/bot/__main__.py", line 17, in <module>
2022-01-17T09:10:39.252569+00:00 app[web.1]:     from .helper.telegram_helper.bot_commands import BotCommands
2022-01-17T09:10:39.252570+00:00 app[web.1]:   File "/usr/src/app/bot/helper/telegram_helper/bot_commands.py", line 1, in <module>
2022-01-17T09:10:39.252572+00:00 app[web.1]:     from bot import BOT_NO
2022-01-17T09:10:39.252572+00:00 app[web.1]: ImportError: cannot import name 'BOT_NO' from 'bot' (/usr/src/app/bot/__init__.py)

### Additional info

.

**Comment by tmatzxzone** [comment]
2022-01-17T10:07:49.128895+00:00 app[web.1]: Traceback (most recent call last):
2022-01-17T10:07:49.128900+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
2022-01-17T10:07:49.128900+00:00 app[web.1]:     return _run_code(code, main_globals, None,
2022-01-17T10:07:49.128901+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
2022-01-17T10:07:49.128901+00:00 app[web.1]:     exec(code, run_globals)
2022-01-17T10:07:49.128902+00:00 app[web.1]:   File "/usr/src/app/bot/__main__.py", line 18, in <module>
2022-01-17T10:07:49.128903+00:00 app[web.1]:     from .helper.telegram_helper.message_utils import sendMessage, sendMarkup, editMessage, sendLogFile
2022-01-17T10:07:49.128903+00:00 app[web.1]:   File "/usr/src/app/bot/helper/telegram_helper/message_utils.py", line 1
2022-01-17T10:07:49.128904+00:00 app[web.1]:     import time import sleep
2022-01-17T10:07:49.128904+00:00 app[web.1]:                 ^
2022-01-17T10:07:49.128904+00:00 app[web.1]: SyntaxError: invalid syntax
