### ISSUE TITLE
New update crashing on Heroku (syntax error)

### ISSUE THREAD

**Issue by tmatzxzone** [Appeza/tg-mirror-leech-bot#27]
### Describe the Bug

Cant deploy on heroku and keep crashing

### Add Logs

2022-01-17T11:56:03.742514+00:00 app[web.1]: Traceback (most recent call last):
2022-01-17T11:56:03.742515+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
2022-01-17T11:56:03.742515+00:00 app[web.1]:     return _run_code(code, main_globals, None,
2022-01-17T11:56:03.742516+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
2022-01-17T11:56:03.742517+00:00 app[web.1]:     exec(code, run_globals)
2022-01-17T11:56:03.742519+00:00 app[web.1]:   File "/usr/src/app/bot/__main__.py", line 18, in <module>
2022-01-17T11:56:03.742521+00:00 app[web.1]:     from .helper.telegram_helper.message_utils import sendMessage, sendMarkup, editMessage, sendLogFile
2022-01-17T11:56:03.742521+00:00 app[web.1]:   File "/usr/src/app/bot/helper/telegram_helper/message_utils.py", line 1
2022-01-17T11:56:03.742521+00:00 app[web.1]:     import time import sleep
2022-01-17T11:56:03.742521+00:00 app[web.1]:                 ^
2022-01-17T11:56:03.742522+00:00 app[web.1]: SyntaxError: invalid syntax

### Additional info

`import time import sleep` in 

> bot/helper/telegram_helper/message_utils.py

shown syntax error

**Comment by missemily2022** [comment]
@tmatzxzone Use "from time import sleep"
