### ISSUE TITLE
Python package error

### ISSUE THREAD

**Issue by NandiyaLive** [Appeza/tg-mirror-leech-bot#32]
### Describe the Bug

I get a python package error when try to run the docker container

### Add Logs

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/app/bot/__main__.py", line 15, in <module>
    from wserver import start_server_async
ModuleNotFoundError: No module named 'wserver'
```

### Additional info

No additional info

**Comment by Tanujairam-TG** [comment]
I am also getting this same error
